### ISSUE TITLE
Cannot install with pip.

### ISSUE THREAD

**Issue by Meganium97** [Aloereed/ultimatevocalremovergui-directml#6]
Here is the output. Any ideas?
```Collecting sklearn
  Using cached sklearn-0.0.post4.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-rlad244x\sklearn_c6d56b9e2fe941c280df29fa68f0a96f\setup.py", line 10, in <module>
          LONG_DESCRIPTION = f.read()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 7: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

S:\AI\ultimatevocalremovergui-directml>

**Comment by Rocketboy235** [comment]
Yeah I got the same thing earlier. If you get this, you should pip install scikit-learn
https://stackoverflow.com/questions/76014260/getting-error-while-installing-sklearn-python-setup-py-egg-info-did-not-run-su and then try running UVR

**Comment by donnyddd** [comment]
> Yeah I got the same thing earlier. If you get this, you should pip install scikit-learn https://stackoverflow.com/questions/76014260/getting-error-while-installing-sklearn-python-setup-py-egg-info-did-not-run-su and then try running UVR

im glad you answered to this so i did use pip install scikit-learn and its still showing me the same error 
maybe you or anyone have an idea why?

**Comment by Rocketboy235** [comment]
Yeah. You will still get that error if you try to do pip install -r requirements.txt.

Are you able to at least run UVR though? I was able to after all of that. I think I also had to manually go and install the packages individually which was weird since requirements.txt should have included those packages but maybe that error was throwing it off

**Comment by donnyddd** [comment]
> Yeah. You will still get that error if you try to do pip install -r requirements.txt.
> 
> Are you able to at least run UVR though? I was able to after all of that. I think I also had to manually go and install the packages individually which was weird since requirements.txt should have included those packages but maybe that error was throwing it off

please assume i dont know anything about coding and explain it like im 5 years old lol 
so i investigated a bit more first of all i dont know why this pops up right at the beginning of trying to do pip install -r requirements.txt  
F :\ultimatevocalremover\ultimatevocairemovergui-directml-master>pip install -r requirements.txt Ignoring SoundFile: markers 'sys_platform == "windows"' don't match your environment
so i dont know if that is relevant

so i tried this 
F :\ultimatevocalremover\ultimatevocalremovergui-directml-master>pip install PySoundFile==0.9.0.postl; sys_platform != 'w indows'
ERROR: Invalid requirement: '!='

and this 
F :\ultimatevocalremover\ultimatevocairemovergui-directml-master>pip install SoundFile==0.9.0; sys_platform == 'windows'
ERROR: Invalid requirement: '=='

and i just tried Python UVR.py like you suggested to see if it works but it gives me this reponse

F :\ultimatevocalremover\ultimatevocalremovergui-directml-master>Python UVR.py Traceback (most recent call last):
File "F:\ultimatevocalremover\ultimatevocalremovergui-directml-master\UVR.py", line 2, in <module> import audioread
ModuleNotFoundError: No module named 'audioread'

thanks for trying to help

edit: ok i just realised what you meant by installing all the packages manually lol so im gonna do that and see if it works then

**Comment by Rocketboy235** [comment]
Sounds good. To save time, you could try deleting the problematic lines in the requirements.txt like delete the sklearn and sysplatform lines so it will at least install the other modules no problem. Then you can manually install the remaining few packages. Hopefully that will save you time in installing the packages.

**Comment by donnyddd** [comment]
ok so Python UVR.py works now and its starting UVR but now when i try to process a track i get this error
https://i.imgur.com/ykz9Nfy.png

edit:
ok since i was confused about pip install torch-directml uninstalling and installing a newer version of torch i figured it must have something to do with that

so i tried to find a older version of torch-directml
pip install torch-directml==0.1.13.1.dev230413

i did that and now i can process tracks with the gpu

seriously thanks for your help and quick responses without you hinting at manually installing the packages i probably wouldnt have get this to work !
